[application]
name = "mitdevcat"
default_platform = "web"

[web.app]
title = "MitDevcat"

[web.watcher]
watch_path = ["src", "assets", "i18n"]

[web.resource]
# CSS files
style = [
    "assets/main.css", 
    "assets/styles/header.css", 
    "assets/styles/hero.css", 
    "assets/styles/animations.css"
]

[web.resource.dev]
# Development CSS files  
style = [
    "assets/main.css", 
    "assets/styles/header.css", 
    "assets/styles/hero.css", 
    "assets/styles/animations.css"
]

[bundle]
out_dir = "docs"
