[application]
name = "mitdevcat"
default_platform = "web"

[web.app]
title = "MitDevcat"
base_path = "mitdevcat"  # Cambia esto por el nombre de tu repositorio

[web.watcher]
watch_path = ["src", "assets"]

[web.resource]
dev = true
style = ["assets/main.css", "assets/styles/header.css", "assets/styles/animations.css"]

[web.proxy]

[bundle]
out_dir = "docs"  # GitHub Pages leerá desde la carpeta docs
